### ISSUE TITLE
Incorrect placement of theme.properties file?

### ISSUE THREAD

**Issue by ShokiTokunaga** [mesutpiskin/keycloak-2fa-email-authenticator#51]
It seems that the `theme.properties` file is placed incorrectly.
Currently, the file is located at `src/main/resources/theme/email-code-theme/theme.properties`, but I believe the correct path should be `src/main/resources/theme/email-code-theme/email/theme.properties`.

In the current location, when the email theme is set to `email-code-theme`, sending emails other than the Email OTP (such as Test Connection or Forgot Password) results in errors.
However, after moving the file to the `email/` directory, these errors were resolved, and the email functionality started working correctly.

Could you please verify if the `theme.properties` file is placed in the correct location?

Lastly, I would like to mention that since I’m not very confident in my English skills, I used AI to help me write this Issue.
I hope everything is clear!

**Comment by OrgesKreka** [comment]
@ShokiTokunaga for me it is not working!
Still i cannot send test email or other emails even after placing theme.properties in the path that you mentioned.

**Comment by ShokiTokunaga** [comment]
The solution I proposed was effective as of commit 846531e6ee302b154d86614dd8bf7523d52012d2, but it seems the issue was resolved differently in issue #54.
With the latest commit (f0356a6fc685c0fd412cf33da10d7b52e39ef00a), the problem no longer occurs without additional changes.
I’ll go ahead and close this issue.
